# Generated by Django 5.0.1 on 2024-01-19 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Commen",
            new_name="Comment",
        ),
    ]
